[menus]
  [[menus.footer]]
    name = 'Legal'
    pageRef = '/legal'
    weight = 10
  [[menus.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Résumé'
    pageRef = '/'
    weight = 20
  [[menus.main]]
    name = 'Projects'
    pageRef = '/'
    weight = 30
  [[menus.main]]
    name = 'Certifications'
    pageRef = '/'
    weight = 40
  [[menus.main]]
    name = 'Notes'
    pageRef = '/'
    weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
